import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased}`}
      >
        <nav className="bg-gray-900 text-white p-4">
          <ul className="flex justify-between">
            <li className="mr-4">
              <a href="/" className="text-lg font-bold">Home</a>
            </li>
            <li>
              <a href="/pokemon-history" className="text-lg font-bold">Pokémon History</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
